version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - emotorad-cloud-network
  emqx:
    image: emqx/emqx
    container_name: emqx
    ports:
      - "1883:1883"  # MQTT
      - "8083:8083"  # MQTT over WebSocket
      - "8084:8084"  # Dashboard
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx
      - EMQX_NODE__DIST_LISTEN_MIN=9100
      - EMQX_NODE__DIST_LISTEN_MAX=9109
    networks:
      - emotorad-cloud-network
  emotorad:
    container_name: emotorad
    build:
      context: ./emotorad-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - emotorad-cloud-network
networks:
  emotorad-cloud-network: